
services:
  nextjs-tube:
    image: jimchen2/nextjs-tube:latest-arm
    ports:
      - '1240:3000'
    env_file:
      - .env  # Environment variables file
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
